
export const TournamentsData = [
  {
    title: "FIFA Masters Cup",
    date: "2024-05-10",
    location: "Karachi, PK",
    attendees: 200,
    googleMapLink: "https://maps.google.com/example2",
    game: "FIFA",
    gameVersion: "FIFA 24",
    category: "Sports",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Tekken World Tour",
    date: "2024-06-18",
    location: "Islamabad, PK",
    attendees: 120,
    googleMapLink: "https://maps.google.com/example3",
    game: "Tekken",
    gameVersion: "Tekken 7",
    category: "Fighting",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Call of Duty: Warfare Arena",
    date: "2024-07-22",
    location: "Dubai, UAE",
    attendees: 300,
    googleMapLink: "https://maps.google.com/example4",
    game: "Call of Duty",
    gameVersion: "Modern Warfare II",
    category: "FPS",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "DOTA 2 Championship",
    date: "2024-09-05",
    location: "Cairo, EG",
    attendees: 500,
    googleMapLink: "https://maps.google.com/example5",
    game: "DOTA 2",
    gameVersion: "7.33c",
    category: "MOBA",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "League of Legends Clash",
    date: "2024-08-19",
    location: "Riyadh, SA",
    attendees: 450,
    googleMapLink: "https://maps.google.com/example6",
    game: "League of Legends",
    gameVersion: "13.15",
    category: "MOBA",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Overwatch League Finals",
    date: "2024-11-02",
    location: "Abu Dhabi, UAE",
    attendees: 250,
    googleMapLink: "https://maps.google.com/example7",
    game: "Overwatch",
    gameVersion: "Overwatch 2",
    category: "FPS",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Valorant Champions Cup",
    date: "2024-10-14",
    location: "Doha, QA",
    attendees: 320,
    googleMapLink: "https://maps.google.com/example8",
    game: "Valorant",
    gameVersion: "6.11",
    category: "FPS",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "PUBG Mobile Showdown",
    date: "2024-12-09",
    location: "Karachi, PK",
    attendees: 400,
    googleMapLink: "https://maps.google.com/example9",
    game: "PUBG Mobile",
    gameVersion: "2.7",
    category: "Battle Royale",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Fortnite Battle Bash",
    date: "2024-01-29",
    location: "Jeddah, SA",
    attendees: 380,
    googleMapLink: "https://maps.google.com/example10",
    game: "Fortnite",
    gameVersion: "Chapter 4",
    category: "Battle Royale",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  }
];



export const gamesCardData = [
  {
    id: 1,
    title: "Super Smash Bros. Ultimate",
    image: "https://www.bing.com/th?pid=Sgg&qlt=100&u=https%3A%2F%2Fimages.start.gg%2Fimages%2Fvideogame%2F1386%2Fimage-d24f740623a31f9e1eec2aabc30f4ba2-optimized.jpg&ehk=Cv4voljXe9IIL1YmYNqg162zjL1hDYQvuyujRyflMX4%3D&w=144&h=192&r=0",
  },
  {
    id: 2,
    title: "Street Fighter 6",
    image: "https://www.bing.com/th?pid=Sgg&qlt=100&u=https%3A%2F%2Fimages.start.gg%2Fimages%2Fvideogame%2F43868%2Fimage-983f6864d7ceec4eba46f2b1f2f96376-optimized.png&ehk=NyI804ksN7oS9PNRBRqfpr7bJ2%2FrjarPE4tZCMMPfjs%3D&w=144&h=192&r=0",
  },
  {
    id: 3,
    title: "TEKKEN 8",
    image: "https://www.bing.com/th?pid=Sgg&qlt=100&u=https%3A%2F%2Fimages.start.gg%2Fimages%2Fvideogame%2F49783%2Fimage-acc13f09acce9819aa908ba77d621a05-optimized.jpg&ehk=xnCM%2FeDWTNnEiVwwtXti50eZLgSc%2B6pb%2BTs2Do8O0Ks%3D&w=144&h=192&r=0",
  },
  {
    id: 4,
    title: "Super Smash Bros. Melee",
    image: "https://www.bing.com/th?pid=Sgg&qlt=100&u=https%3A%2F%2Fimages.start.gg%2Fimages%2Fvideogame%2F1%2Fimage-36450d5d1b6f2c693be2abfdbc159106-optimized.jpg&ehk=CRpoBnGE8dtJkSIGcd2811UkurtlEPOKEay%2BqgCETlQ%3D&w=144&h=192&r=0",
  },
  {
    id: 5,
    title: "MultiVersus",
    image: "https://www.bing.com/th?pid=Sgg&qlt=100&u=https%3A%2F%2Fimages.start.gg%2Fimages%2Fvideogame%2F40849%2Fimage-5e7bc5dfb394d2cf8bb366dcee8672c0-optimized.jpg&ehk=n2OaDj6a3hMRnErF9sqNwkD56Z%2B3otD7a8fuhA6ewOc%3D&w=144&h=192&r=0",
  },
]

export const tournamentsCardData = [
  {
    id: 1,
    title: "World Warrior 2024 - Japan 4",
    date: "Nov 16th — 17th, 2024",
    location: "Online",
    events: 1,
    image: "https://images.start.gg/images/tournament/681774/image-b2e6d031b7b3006085fb051871787141-optimized.png?ehk=baoYmJL5tgcYRKq0kfSYnFU2qlJ%2BAkQK6gFehYmMBiE%3D&ehkOptimized=1TXXUEYeCR98x9xXaSSO%2FEBhVHUVmHEjvPEbHTrFkfk%3D",
  },
  {
    id: 2,
    title: "BATTLE COLISEUM 2024",
    date: "Nov 15th — 17th, 2024",
    location: "Liberdade, BR",
    events: 9,
    image: "https://images.start.gg/images/tournament/700259/image-8a2242a6d5d05604816b5753f53b5f9f-optimized.png?ehk=Qws2dQm%2BnRJfuLBf0%2FuIR14qwtF0JDD2AYTq%2Btxf4dw%3D&ehkOptimized=i513EiCDhx0PKjCLJznvWXRYjS%2FTOHdeonMDAgCaWts%3D",
  },
]
