
export const TournamentsData = [
  {
    title: "FIFA Masters Cup",
    date: "2024-05-10",
    location: "Karachi, PK",
    attendees: 200,
    googleMapLink: "https://maps.google.com/example2",
    game: "FIFA",
    gameVersion: "FIFA 24",
    category: "Sports",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Tekken World Tour",
    date: "2024-06-18",
    location: "Islamabad, PK",
    attendees: 120,
    googleMapLink: "https://maps.google.com/example3",
    game: "Tekken",
    gameVersion: "Tekken 7",
    category: "Fighting",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Call of Duty: Warfare Arena",
    date: "2024-07-22",
    location: "Dubai, UAE",
    attendees: 300,
    googleMapLink: "https://maps.google.com/example4",
    game: "Call of Duty",
    gameVersion: "Modern Warfare II",
    category: "FPS",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "DOTA 2 Championship",
    date: "2024-09-05",
    location: "Cairo, EG",
    attendees: 500,
    googleMapLink: "https://maps.google.com/example5",
    game: "DOTA 2",
    gameVersion: "7.33c",
    category: "MOBA",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "League of Legends Clash",
    date: "2024-08-19",
    location: "Riyadh, SA",
    attendees: 450,
    googleMapLink: "https://maps.google.com/example6",
    game: "League of Legends",
    gameVersion: "13.15",
    category: "MOBA",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Overwatch League Finals",
    date: "2024-11-02",
    location: "Abu Dhabi, UAE",
    attendees: 250,
    googleMapLink: "https://maps.google.com/example7",
    game: "Overwatch",
    gameVersion: "Overwatch 2",
    category: "FPS",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Valorant Champions Cup",
    date: "2024-10-14",
    location: "Doha, QA",
    attendees: 320,
    googleMapLink: "https://maps.google.com/example8",
    game: "Valorant",
    gameVersion: "6.11",
    category: "FPS",
    registrationOpen: false,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "PUBG Mobile Showdown",
    date: "2024-12-09",
    location: "Karachi, PK",
    attendees: 400,
    googleMapLink: "https://maps.google.com/example9",
    game: "PUBG Mobile",
    gameVersion: "2.7",
    category: "Battle Royale",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  },
  {
    title: "Fortnite Battle Bash",
    date: "2024-01-29",
    location: "Jeddah, SA",
    attendees: 380,
    googleMapLink: "https://maps.google.com/example10",
    game: "Fortnite",
    gameVersion: "Chapter 4",
    category: "Battle Royale",
    registrationOpen: true,
    image: "https://www.start.gg/__static/images/fallback/tournament.svg",
  }
];
